### PR TITLE
Groot partials

### PR DESCRIPTION
**Pull request by anniavdc**
Hello! Can you please check this partials js????

### CODE REVIEW

**Review by mirenguerra — COMMENTED** [review]
We've checked your partials. They look good. The object could be in a new partial called 'model' or something like this and the partial main could be empty. The indent maybe fix our merge. Good job!

**Comment by anniavdc** [comment]
Done, now we'll merge groot into out branch to solve conflicts if you think it's ok

**Comment by mirenguerra** [comment]
Ok, you could resolve the conflicts and merge.

**Comment by anniavdc** [comment]
Hi, we've merge groot-partials with groot through the console because it was complicated doing it with github. So, we've solved the conflicts and it's all set.

**Pull request merged**
