### PR TITLE
w3 check done

### PR DESCRIPTION
**Pull request by claramiralles**
Hi! I have passed all the main.js in w3check. I corrected a small typo correction in use strict and some white spaces that the checker was pointing. Of course it also pointed to the comments, but nothing else about the code itself :)

### CODE REVIEW

**Comment by claramiralles** [comment]
Hi! I have passed all the main.js in w3check. I corrected a small typo correction in use strict and some white spaces that the checker was pointing. Of course it also pointed to the comments, but nothing else about the code itself :) @sandrapinazo can you please review it?

**Comment by claramiralles** [comment]
Checked with w3 checker the html. Changed some small details:
- changed label for to github with not capital letter as in id of input at form-fill partial html
- add alt to img iin html partial _footer.html
@anniavdc if you can please review and we merge

**Comment by anniavdc** [comment]
Hi Clara, thanks!. Did you check if that ID of input that you changed wasn't in main.js ? I mean because if it's an input that we used for events with it's corresponding ID maybe it could have breaked something. If you can review it or tell me witch ID was it I can also check the code

**Comment by anniavdc** [comment]
Sorry, I think I missunderstood you with this:
changed label for to github with not capital letter as **_in id of input at form-fill partial html_** but I checked the files changed and your commits and it seems it was only the label. So I believe you can merge, after you do this, check if everything it's working in master and do a gulp docs, so it's updated

**Pull request closed without merging**
